### ISSUE TITLE
Cover device states not reflecting 'position' in HA

### ISSUE THREAD

**Issue by arrikhan** [autoSteve/acMqtt#30]
My cover devices are not reflecting the correct 'state' in relation to their position. Is this controlled/managed in your scripts/discovery? I think HA flipped this recently?

<img width="764" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/c02b802e-f5d5-47b4-a1fe-31cac1027305">

<img width="674" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/93b67d51-7da4-4272-9f22-33db334283d1">

I use window winders on a switch relay to open/close windows.

CLOSED = 0
OPEN = ~255/100%

I also have Blinds on a similar setup 

CLOSED = 0 
OPEN = 255/100%

Is there a way to ensure correct states are represented in HA so that I can control correctly?

**Comment by arrikhan** [comment]
Further investigation is showing the CBUS topic has the following value when the window is closed;

```
cbus/read/0/56/31/level
0
```


and the homeassistant/cover/cbus_mqtt_254/56_1 topic value is;


```
{"pos_open":255,"ic":"mdi:lightbulb","uniq_id":"cbus_mqtt_254_56_37","dev":{"ids":" Hallway Window","mdl":"CBus","sa":"","mf":"Schneider Electric","name":"Hallway Window"},"pos_t":"cbus\/read\/0\/56\/37\/level","obj_id":"cbus_mqtt_254_56_37","stat_t":"cbus\/read\/0\/56\/37\/state","cmd_t":"cbus\/write\/0\/56\/37\/ramp","avty_t":"cbus\/status","set_pos_t":"cbus\/write\/0\/56\/37\/ramp","pl_cls":"CLOSE","pos_clsd":0,"name":"","pl_open":"OPEN"}
```

And Home Assistant Entity shows

<img width="772" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/b7ae259c-de0e-4900-8ed9-78f84514f0bb">

**Comment by autoSteve** [comment]
This is an interesting quirk of how the CBus blind controller works in level translation mode, and this is less than ideal for HA.

Level translation behaviour is used when the 'cover' keyword is employed. In short, the script sets various levels for up/down/stop. 0=closed, 255=open, 5=stop, and this makes HA slider status weird. The slider does work to set an arbitrary position, but as soon as 0, 255 or 5 (or OPEN, CLOSE, STOP commands) is seen the status can get weird, especially when using STOP.

So I do not use 'cover'. Because I mostly hate it as there is no feedback from the blind relay about how 'open' a blind is when stopped at a given position.

I thought about using funky timing to estimate how 'open' a blind was, and then when a STOP was received have acMqtt set the level of the blind to that estimate. Getting the timing right would be a nightmare for differing blind motors and motor age, and would likely involve quite a bit of calibration and recalibration over time. So I didn't.

Instead I use a 'select' keyword to set the blind at various preset openings. In my case these are levels 0, 137, 255.

MQTT, select, sa=Bathroom 2, lvl=Closed/Half open/Open, 

An alternative would be to just use a slider.

MQTT, light, sa=Bathroom 2, img=mdi:blinds,

**Comment by arrikhan** [comment]
I only use two positions .. open/closed. So if I set lvl=Closed/Open and use select keyword.. will this fix this?

Also, what is the correct steps to push through keyword changes?

**Comment by arrikhan** [comment]
I should correct my above statement, I'm using CBUS shutters for both cover items so having a slider will work for me. 

ie: 0-255 are predetermined states/positions

Should cover work under this circumstance?

**Comment by autoSteve** [comment]
If the level tags are set for the object (i.e. level 0 = "Closed" and 255 = "Open"), then yes. If there are no level tags (or you don't want to set them up) you could use lvl=0/255.

By default the script will check for keyword changes every 30 seconds. I actually have this set at five seconds at the moment, checking for performance impact. There seems to be none.

(In setting up here for level translation mode I did notice that change detection messed something up re. cover, so I need to fix that. **I would advise you to restart MQTT send receive for now after making that cover shange**.)

If you're using a slider or select then turn off level translation mode on the blind relay.

Switch 'off' will be closed. 'On' will be open. Or a slider value for somewhere inbetween.

Note also that I think the code is employing 'last level' for blinds. I will need to check this. So if a blind is set to half open, then you close it and it will close, and then you open it again it will likely return to the last intermediate opened level. Check this to see if I'm right.

**Comment by autoSteve** [comment]
Actually, returning to the previous level is being done by Home Assistant!

**Comment by arrikhan** [comment]
Ok I have tried this category setting which works whenever you reset the send receive script...  but not when interacting with device in HA. 

ie: I move slider left/right it opens/closes but the state isn't updated correctly. When I restart script it updates to correct state as per setting.?! Note I've tried a range here because sometimes my windows only get to 249 :/. I have been testing Blinds with "255:open" and get same result.

`MQTT, cover, img=mdi:window-closed, lvl=0:"Closed"/249-255:"Open", 
`

<img width="243" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/f4bdc89f-6fed-4436-968f-b37f7aaf307d">

**Comment by autoSteve** [comment]
Per README.md:

MQTT, **light**, img=mdi:window-closed, (a slider with on/off toggle, remembering prior open level)
or
MQTT, **select**, img=mdi:window-closed, lvl=Closed:0/Open:255, (a select of Closed or Open state)

No quotes. No ranges. And you had the name/level the wrong way around.

lvl= is only for use with trigger app button, select and lighting app _sensors_ only

**Comment by arrikhan** [comment]
Unfortunately I cannot use slider feature on tile in HA when device is not set to COVER. This is why I was playing with that combo to see what would happen.

So maybe I dont understand the problem fully then. 

Setting it back to basic COVER. 

When I restart script , the state in the entity updates in HA (then reflects on tile in dashboard) but not before. Even an update of the category in SHAC forces a refresh of that state. 

Is HA determining that state or is that something setup by your configuration? 

1. If it's HA ... then something is weird in HA as the position is correct in the entity whilst the state doesn't change.
2. If it's your script refreshing state based on position .. then on changing the position is your script not updating state like it does on a restart of script?

**Comment by autoSteve** [comment]
Questions:

1. What sort of card is that? (I'd like to try and replicate this behaviour.)
2. Is your blind relay configured in level translation mode? (Global tab in unit properties in Toolkit.)
3. I cannot get my head around the sequence involved: _"When I restart script , the state in the entity updates in HA (then reflects on tile in dashboard) but not before. Even an update of the category in SHAC forces a refresh of that state."_ A step-by-step of the exact sequence to replicate would be appreciated.

**Comment by arrikhan** [comment]
> Questions:
> 
> 1. What sort of card is that? (I'd like to try and replicate this behaviour.)

I'm using a tile card in a grid card setup in my screen captures. The features are a part of the TILE card.

https://www.home-assistant.io/dashboards/features/

> 2. Is your blind relay configured in level translation mode? (Global tab in unit properties in Toolkit.)

Yes it is. This was a default setting I left as it when it was setup.

NOTE: I have a lighting group (Kitchen Windows) that controls 4 individual shutters (4 windows) and a lighting group (Kitchen Blinds) that controls 2 individual shutters (2 blinds) but all the HA config is against the each group obviously.

> 3. I cannot get my head around the sequence involved: _"When I restart script , the state in the entity updates in HA (then reflects on tile in dashboard) but not before. Even an update of the category in SHAC forces a refresh of that state."_ A step-by-step of the exact sequence to replicate would be appreciated.

Sure thing.. 

Starting position with correct status.

<img width="248" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/6c96ab40-f1f8-4e25-908e-fabe1971e732">

<img width="670" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/8c7f8062-12de-4f94-98aa-684e231c5e25">


1. I shift slider (windows) on dashboard to alternate position. (current position changes, state does not)

<img width="250" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/80f8d25e-0c0f-4837-af49-773aa6d48258">

<img width="669" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/260444a0-b0ec-406b-b069-65f6eebaae0c">

2. Disable/Enable send receive script in SHAC5500

<img width="1417" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/b4d8f218-9fdc-4e8f-ac9d-ed72d9bae76d">

3. Watch HA update dashboard/entity state (state updates to correct value)

<img width="255" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/953437b3-82df-4d6c-a16d-8b499da81d3e">

<img width="666" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/614f449f-f517-41e5-bd2e-003fad40761d">


The Entity "STATE" as seen in the states view under developer tools shows state and values as they change dynamically.

**Comment by autoSteve** [comment]
Brilliant. I see the issue...

The weird thing about this is re-starting the script does not update the topic state. This is Home Assistant changing the visible state.

<img width="1089" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/99b75adc-eed8-4d9b-8dfe-3e0516718ebc">

**Comment by autoSteve** [comment]
Replace line 359 (currently state = 'stopped') with this:

```
state = (tonumber(level) ~= 0) and 'open' or 'closed'
```

**Comment by arrikhan** [comment]
> Replace line 359 (currently state = 'stopped') with this:
> 
> ```
> state = (tonumber(level) ~= 0) and 'open' or 'closed'
> ```

Perfect!

**Comment by autoSteve** [comment]
Hey @arrikhan.

There is a new commit. You will need to add a keyword for your covers. Without this keyword the script assumes level translation mode is being used and your status will be messed up. When the keyword is added the level=5 for a STOP command is ignored, and the MQTT state is updated to 'open' or 'closed' (without it, state is 'stopped').

```
MQTT, cover, sa=Bathroom 2, noleveltranslate, 
```

Don't forget to update to this latest commit with the new keyword, or when you update in future your covers will break!

Once you've verified that all is well with the new commit I'll close this issue.

**Comment by arrikhan** [comment]
Done .. and thanks for all your work on this!

All working as expected.

**Comment by autoSteve** [comment]
Sweet.

I'm going to leave this issue open for now, and have another go at tracking blind position with timing, given CBus blind controllers do not report status. This has bothered me for years.

My plan is to add a speed calibration keyword for cover, something like rate=16.4 to indicate that going from open to closed takes 16.4 seconds for that cover. Assuming linear rate of travel an approximate openness could be calculated, and with frequent broker updates the slider would move by itself when 'up' or 'down' were pressed, stopping whenever the 'stop' button is pressed. Touching the slider during opening or closing would cancel the timed position updates and set an actual position.

Sounds like a plan.

<img width="498" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/3e87fa68-8ac4-458e-aa48-5058829f2399">

**Comment by autoSteve** [comment]
Note that I missed a change in the latest commit. Periodic create/update/delete will ignore the new noleveltranslate keyword changes. It'll make it in there soon. If this is important to you, at line 114 replace this variable... Oops.

```
local cudRaw = {             -- All possible keywords for MQTT types, used in CUD function to exclude unrelated keywords for change detection
  'MQTT', 'light', 'switch', 'cover', 'fan', 'fan_pct', 'fanpct', 'sensor', 'binary_sensor', 'binarysensor', 'bsensor', 'button', 'select',
  'pn=', 'sa=', 'img=', 'unit=', 'class=', 'dec=', 'scale=', 'on=', 'off=', 'lvl=', 'rate=',
  'includeunit', 'preset', 'noleveltranslate',
}
```

**Comment by autoSteve** [comment]
Righto @arrikhan.

If you're up for a testing challenge...

The latest commit introduces a concept called 'cover tracking'. This attempts to get HA status correct for the open position of a cover during a transition. Theory of operation just like my plan said.

There are three possible modes of cover operation:
1. The way you have it set now, with 'noleveltranslate'. No change.
2. Level translate mode, so without that keyword
3. Level translate mode with tracking

None of this is in the readme yet.

The way level translate _without tracking_ works is just better than it was before. Clicking open sets the slider to 0%, then when stop is hit at an intermediate point the slider goes 50%, or if fully open stays at 0%. The reverse is true for close. Status and operation is bi-directional CBus/HA. This is far superior in terms of status in HA, even if not really correct.

The way level translation _with tracking_ works requires some calibration to get right. The steps:
1. Time how long it takes the cover to close.
2. Time how long it takes to open.
3. Add these (probably rough) numbers to a rate=up/down keyword. Example for one of my Somfy blinds: rate=15.91/15.85, which started out at a rough rate=16/16. You can also just specify one rate value (e.g. rate=16) and the same will be used for open and close.
4. Test and tweak. What I did was to start fully open, then close to just about the bottom. The blind then jerked either upwards or downwards a little bit, telling me the timing was not quire right. Adjust rate, and rinse/repeat, doing the same for opening on the other way up. It didn't take long. On closing, if it jerks up, it means the rate value is too low, and jerks down the opposite. On opening, if it jerks up the rate is too high, jerks down too low.
5. Then if the (always) tweak a little bit on stop is not desired, because tracking will never be 100%, then set a variable near the top of the script to false (setCoverLevelAtStop)

There is also another keyword delay=, which I am not using but is implemented. If there is a small delay before the cover begins its travel then this will delay tracking for that period. It's good for 1/10th of a second resolution.

So if you're up for it then give transition tracking a go!

**Comment by autoSteve** [comment]
Readme updated.

**Comment by arrikhan** [comment]
Hi Steve,

My blinds are set with max/min limits so I am not sure if my testing will help. 

My windows open to the fullest extension of the electronic winder.. and back in again until it stops. This could help?

**Comment by autoSteve** [comment]
So for the blinds, you would need a min and max setting for travel. Let's say min 0, and max 251, yeah?. I might be able to implement keywords to suit that to limit the range of what is considered 100%, along with a position_template in discovery, given more information about what you've got set up. Anything is possible, within reason. It's just code.

For the windows, 0-255? If so, that'd work for some testing beyond just me.
